### ISSUE TITLE
use argparse in data_generator.py

### ISSUE THREAD

**Issue by theRemix** [chalmerlowe/data_generator#5] opened 2015-08-24 07:39 UTC
i don't know how to use args.py

add argparse and help options to data_generator.py

**Comment by chalmerlowe** [comment] 2015-08-24 17:54
Gonna close this as a semi duplicate of Issue #3 
Args.py is intended to separate the functionality of parsing args from the functionality of generating data.

**Closed as completed by chalmerlowe** 2015-08-24 17:54 UTC

**Comment by theRemix** [comment] 2015-08-24 22:00
ah yes, that is what it looked like, and it also looked unfinished.

i don't know how i would use args.py to call the data_generator.py file with optional arguments, so i'll leave that up to you.

when you do finish it, please update the readme on how to use both.
